apiVersion: apps/v1
kind: Deployment
metadata:
  name: sharma-micro
  labels:
    app: sharma-micro
  namespace: sharma  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sharma-micro
  template:
    metadata:
      labels:
        app: sharma-micro
    spec:
      containers:
        - name: sharma-micro
          image: ramann123/raman-customer-orders-service2:latest
          ports:
            - containerPort: 5000
          resources:
            limits:
              cpu: "100m"
              memory: "100Mi"
