apiVersion: v1
kind: Service
metadata:
  name: sharma-micro
  namespace: sharma
spec:
  selector:
    app: sharma-micro
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort
